/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_LORA_PACKET_PB_H_INCLUDED
#define PB_LORA_PACKET_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RoverData {
    float latitude; /* degrees */
    float longitude; /* degrees */
    uint32_t heading; /* degrees, fixed-point decimal with 0.1 precision */
    uint32_t heel; /* degrees, fixed-point decimal with 0.1 precision, 0 to 1800 */
    uint32_t cog; /* degrees, fixed-point decimal with 0.1 precision, 0 to 3600 */
    uint32_t sog; /* knots, fixed-point decimal with 0.1 precision */
    uint32_t battery; /* volts, fixed-point decimal with 0.01 precision */
} RoverData;

typedef struct _RoverDiscovery {
    char dummy_field;
} RoverDiscovery;

typedef struct _RoverConfiguration {
    pb_size_t slots_count;
    int32_t slots[100];
    uint32_t sbw;
    uint32_t sf;
} RoverConfiguration;

typedef struct _LoRaPacket {
    uint32_t hardwareID;
    pb_size_t which_payload;
    union {
        RoverData roverData;
        RoverDiscovery roverDiscovery;
        RoverConfiguration roverConfiguration;
    } payload;
} LoRaPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LoRaPacket_init_default                  {0, 0, {RoverData_init_default}}
#define RoverData_init_default                   {0, 0, 0, 0, 0, 0, 0}
#define RoverDiscovery_init_default              {0}
#define RoverConfiguration_init_default          {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0}
#define LoRaPacket_init_zero                     {0, 0, {RoverData_init_zero}}
#define RoverData_init_zero                      {0, 0, 0, 0, 0, 0, 0}
#define RoverDiscovery_init_zero                 {0}
#define RoverConfiguration_init_zero             {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define RoverData_latitude_tag                   1
#define RoverData_longitude_tag                  2
#define RoverData_heading_tag                    3
#define RoverData_heel_tag                       4
#define RoverData_cog_tag                        5
#define RoverData_sog_tag                        6
#define RoverData_battery_tag                    7
#define RoverConfiguration_slots_tag             1
#define RoverConfiguration_sbw_tag               2
#define RoverConfiguration_sf_tag                3
#define LoRaPacket_hardwareID_tag                1
#define LoRaPacket_roverData_tag                 2
#define LoRaPacket_roverDiscovery_tag            3
#define LoRaPacket_roverConfiguration_tag        4

/* Struct field encoding specification for nanopb */
#define LoRaPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  hardwareID,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,roverData,payload.roverData),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,roverDiscovery,payload.roverDiscovery),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,roverConfiguration,payload.roverConfiguration),   4)
#define LoRaPacket_CALLBACK NULL
#define LoRaPacket_DEFAULT NULL
#define LoRaPacket_payload_roverData_MSGTYPE RoverData
#define LoRaPacket_payload_roverDiscovery_MSGTYPE RoverDiscovery
#define LoRaPacket_payload_roverConfiguration_MSGTYPE RoverConfiguration

#define RoverData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude,         2) \
X(a, STATIC,   SINGULAR, UINT32,   heading,           3) \
X(a, STATIC,   SINGULAR, UINT32,   heel,              4) \
X(a, STATIC,   SINGULAR, UINT32,   cog,               5) \
X(a, STATIC,   SINGULAR, UINT32,   sog,               6) \
X(a, STATIC,   SINGULAR, UINT32,   battery,           7)
#define RoverData_CALLBACK NULL
#define RoverData_DEFAULT NULL

#define RoverDiscovery_FIELDLIST(X, a) \

#define RoverDiscovery_CALLBACK NULL
#define RoverDiscovery_DEFAULT NULL

#define RoverConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, INT32,    slots,             1) \
X(a, STATIC,   SINGULAR, UINT32,   sbw,               2) \
X(a, STATIC,   SINGULAR, UINT32,   sf,                3)
#define RoverConfiguration_CALLBACK NULL
#define RoverConfiguration_DEFAULT NULL

extern const pb_msgdesc_t LoRaPacket_msg;
extern const pb_msgdesc_t RoverData_msg;
extern const pb_msgdesc_t RoverDiscovery_msg;
extern const pb_msgdesc_t RoverConfiguration_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LoRaPacket_fields &LoRaPacket_msg
#define RoverData_fields &RoverData_msg
#define RoverDiscovery_fields &RoverDiscovery_msg
#define RoverConfiguration_fields &RoverConfiguration_msg

/* Maximum encoded size of messages (where known) */
#define LoRaPacket_size                          1120
#define RoverConfiguration_size                  1112
#define RoverData_size                           40
#define RoverDiscovery_size                      0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
