/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_LORA_PACKET_PB_H_INCLUDED
#define PB_LORA_PACKET_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* A sample of data from the rover */
typedef struct _RoverData {
    float latitude; /* degrees */
    float longitude; /* degrees */
    uint32_t heading; /* degrees, fixed-point decimal with 0.1 precision */
    uint32_t heel; /* degrees, fixed-point decimal with 0.1 precision, 0 to 1800 */
    uint32_t cog; /* degrees, fixed-point decimal with 0.1 precision, 0 to 3600 */
    uint32_t sog; /* knots, fixed-point decimal with 0.1 precision */
    uint32_t battery; /* percent, 0 implies null */
} RoverData;

/* Message from a newly-powered-on rover, asking base station for configuration */
typedef struct _RoverDiscovery {
    char dummy_field;
} RoverDiscovery;

/* Message from the base station to a new rover, configuring it for communication */
typedef struct _RoverConfiguration {
    /* TDMA slot numbers during which the rover is allowed to send RoverData */
    pb_size_t slots_count;
    int32_t slots[100];
    /* LoRa bandwidth (kHz) when sending RoverData */
    uint32_t sbw;
    /* LoRa spreading factor when sending RoverData */
    uint32_t sf;
} RoverConfiguration;

/* Message from the base station telling a rover to soft-reset and attempt discovery again,
 useful for when the base station has just powered on to ensure that rovers are reinitialized */
typedef struct _RoverReset {
    char dummy_field;
} RoverReset;

typedef struct _LoRaPacket {
    /* The fixed hardware identifier for the rover, based on the serial number of the ARM Cortex chip */
    uint32_t hardware_id;
    pb_size_t which_payload;
    union {
        RoverData rover_data;
        RoverDiscovery rover_discovery;
        RoverConfiguration rover_configuration;
        RoverReset rover_reset;
    } payload;
    /* A logical, human-friendly identifier for the rover */
    uint32_t serial_number;
} LoRaPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LoRaPacket_init_default                  {0, 0, {RoverData_init_default}, 0}
#define RoverData_init_default                   {0, 0, 0, 0, 0, 0, 0}
#define RoverDiscovery_init_default              {0}
#define RoverConfiguration_init_default          {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0}
#define RoverReset_init_default                  {0}
#define LoRaPacket_init_zero                     {0, 0, {RoverData_init_zero}, 0}
#define RoverData_init_zero                      {0, 0, 0, 0, 0, 0, 0}
#define RoverDiscovery_init_zero                 {0}
#define RoverConfiguration_init_zero             {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0}
#define RoverReset_init_zero                     {0}

/* Field tags (for use in manual encoding/decoding) */
#define RoverData_latitude_tag                   1
#define RoverData_longitude_tag                  2
#define RoverData_heading_tag                    3
#define RoverData_heel_tag                       4
#define RoverData_cog_tag                        5
#define RoverData_sog_tag                        6
#define RoverData_battery_tag                    7
#define RoverConfiguration_slots_tag             1
#define RoverConfiguration_sbw_tag               2
#define RoverConfiguration_sf_tag                3
#define LoRaPacket_hardware_id_tag               1
#define LoRaPacket_rover_data_tag                2
#define LoRaPacket_rover_discovery_tag           3
#define LoRaPacket_rover_configuration_tag       4
#define LoRaPacket_rover_reset_tag               6
#define LoRaPacket_serial_number_tag             5

/* Struct field encoding specification for nanopb */
#define LoRaPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  hardware_id,       1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,rover_data,payload.rover_data),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,rover_discovery,payload.rover_discovery),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,rover_configuration,payload.rover_configuration),   4) \
X(a, STATIC,   SINGULAR, UINT32,   serial_number,     5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,rover_reset,payload.rover_reset),   6)
#define LoRaPacket_CALLBACK NULL
#define LoRaPacket_DEFAULT NULL
#define LoRaPacket_payload_rover_data_MSGTYPE RoverData
#define LoRaPacket_payload_rover_discovery_MSGTYPE RoverDiscovery
#define LoRaPacket_payload_rover_configuration_MSGTYPE RoverConfiguration
#define LoRaPacket_payload_rover_reset_MSGTYPE RoverReset

#define RoverData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude,         2) \
X(a, STATIC,   SINGULAR, UINT32,   heading,           3) \
X(a, STATIC,   SINGULAR, UINT32,   heel,              4) \
X(a, STATIC,   SINGULAR, UINT32,   cog,               5) \
X(a, STATIC,   SINGULAR, UINT32,   sog,               6) \
X(a, STATIC,   SINGULAR, UINT32,   battery,           7)
#define RoverData_CALLBACK NULL
#define RoverData_DEFAULT NULL

#define RoverDiscovery_FIELDLIST(X, a) \

#define RoverDiscovery_CALLBACK NULL
#define RoverDiscovery_DEFAULT NULL

#define RoverConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, INT32,    slots,             1) \
X(a, STATIC,   SINGULAR, UINT32,   sbw,               2) \
X(a, STATIC,   SINGULAR, UINT32,   sf,                3)
#define RoverConfiguration_CALLBACK NULL
#define RoverConfiguration_DEFAULT NULL

#define RoverReset_FIELDLIST(X, a) \

#define RoverReset_CALLBACK NULL
#define RoverReset_DEFAULT NULL

extern const pb_msgdesc_t LoRaPacket_msg;
extern const pb_msgdesc_t RoverData_msg;
extern const pb_msgdesc_t RoverDiscovery_msg;
extern const pb_msgdesc_t RoverConfiguration_msg;
extern const pb_msgdesc_t RoverReset_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LoRaPacket_fields &LoRaPacket_msg
#define RoverData_fields &RoverData_msg
#define RoverDiscovery_fields &RoverDiscovery_msg
#define RoverConfiguration_fields &RoverConfiguration_msg
#define RoverReset_fields &RoverReset_msg

/* Maximum encoded size of messages (where known) */
#define LoRaPacket_size                          1126
#define RoverConfiguration_size                  1112
#define RoverData_size                           40
#define RoverDiscovery_size                      0
#define RoverReset_size                          0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
