/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "lora_packet.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LoRaPacket, LoRaPacket, 2)


PB_BIND(RoverData, RoverData, AUTO)


PB_BIND(RoverDiscovery, RoverDiscovery, AUTO)


PB_BIND(RoverConfiguration, RoverConfiguration, 2)



